# Generated by Django 5.1 on 2026-04-27 09:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text='Unique identifier for the permission (e.g., "view_student_grades")',
                        max_length=100,
                        unique=True,
                        verbose_name="Permission Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable permission name",
                        max_length=255,
                        verbose_name="Permission Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this permission allows",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="general",
                        help_text="Permission category for grouping",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                            ("school_admin", "School Administrator"),
                            ("system_admin", "System Administrator"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Role Name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Friendly name shown in UI",
                        max_length=100,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of role responsibilities"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this role can be assigned to users",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=100,
                        help_text="Role hierarchy level (1=highest, 100=lowest)",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions granted to this role",
                        related_name="roles",
                        to="accounts.permission",
                        verbose_name="Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the school or organization",
                        max_length=255,
                        verbose_name="School Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Unique subdomain identifier (e.g., "springfield" for springfield.eduai.com)',
                        max_length=100,
                        unique=True,
                        verbose_name="Subdomain",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text='Optional custom domain (e.g., "school.edu")',
                        max_length=255,
                        null=True,
                        verbose_name="Custom Domain",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive tenants cannot be accessed",
                        verbose_name="Active Status",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="School logo",
                        null=True,
                        upload_to="tenant_logos/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4F46E5",
                        help_text="Primary brand color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="School-specific configuration and preferences",
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
                (
                    "subscription_expires",
                    models.DateTimeField(
                        blank=True, help_text="Subscription expiration date", null=True
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(
                        default=100, help_text="Maximum number of students allowed"
                    ),
                ),
                (
                    "max_teachers",
                    models.IntegerField(
                        default=10, help_text="Maximum number of teachers allowed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_active"], name="accounts_te_slug_7088fc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="User email address (used for login)",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biography"),
                ),
                (
                    "grade_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Current grade level for students",
                        null=True,
                        verbose_name="Grade Level",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="School-assigned student ID",
                        max_length=50,
                        null=True,
                        verbose_name="Student ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="School-assigned employee ID",
                        max_length=50,
                        null=True,
                        verbose_name="Employee ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Subject specialization for teachers",
                        max_length=100,
                        null=True,
                        verbose_name="Specialization",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has verified their email",
                        verbose_name="Email Verified",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Last Login IP"
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User-specific settings and preferences",
                        verbose_name="User Preferences",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role determines permissions and dashboard access",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="accounts.role",
                        verbose_name="User Role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="School this user belongs to (null for system admins)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.tenant",
                        verbose_name="School/Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "is_active"],
                        name="accounts_us_email_f69303_idx",
                    ),
                    models.Index(
                        fields=["tenant", "role"], name="accounts_us_tenant__f32487_idx"
                    ),
                ],
            },
        ),
    ]
