"""Per-Task MCQ quizzes for Hunt nodes.

Every Task on the dungeon map requires the student to pass an MCQ quiz
before it's marked complete. Questions are:

- Curriculum-grounded: generated by QuestionGenerator with `content_context`
  filled from the Task's `ref_node` (or any topic node in the goal's subject
  if no ref). LLM-primary, stub fallback when no OPENAI_API_KEY.
- Cached on `Task.quiz_questions` so retries after a fail show the same
  questions — otherwise students couldn't actually learn from feedback.
- Sized by task kind (see `Task.required_questions`); pass threshold per
  kind (see `Task.pass_threshold_pct`).
"""

from __future__ import annotations

import logging
from typing import Dict, List, Optional

from django.conf import settings

from apps.service.models import ContentNode, Task
from apps.service.services.assessments.question_generator import QuestionGenerator

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# generation
# ---------------------------------------------------------------------------

def _stub_questions(topic_title: str, count: int) -> List[dict]:
    """Offline fallback used whenever the LLM is unavailable."""
    out = []
    for i in range(count):
        out.append({
            'question': (
                f'Which of the following best relates to "{topic_title}"? '
                f'(Q {i + 1})'
            ),
            'options': [
                {'key': 'A', 'text': f'The core idea of {topic_title}'},
                {'key': 'B', 'text': 'A concept from a different chapter'},
                {'key': 'C', 'text': 'A prerequisite from an earlier grade'},
                {'key': 'D', 'text': 'None of the above'},
            ],
            'correct_answer': 'A',
            'explanation': f'"{topic_title}" is the central idea of this task.',
        })
    return out


def _pick_grounding_node(task: Task) -> Optional[ContentNode]:
    """Pick the best ContentNode to ground this task's quiz in."""
    if task.ref_node_id:
        try:
            return ContentNode.objects.get(pk=task.ref_node_id)
        except ContentNode.DoesNotExist:
            pass

    goal = task.goal
    student = goal.student
    if goal.subject_id is None:
        return None

    qs = ContentNode.objects.filter(
        tenant=student.tenant,
        subject_id=goal.subject_id,
        node_type__in=['topic', 'section', 'definition', 'summary'],
    ).exclude(content_plain='')
    return qs.order_by('?').first()


def _normalize_question(raw: dict) -> dict:
    """Coerce whatever QuestionGenerator returned into our canonical shape:
    {question, options=[{key,text}], correct_answer=<KEY>, explanation}."""
    options_raw = raw.get('options') or []
    options: List[dict] = []
    correct_raw = str(raw.get('correct_answer', '')).strip()
    correct_key = 'A'

    for idx, opt in enumerate(options_raw[:4]):
        key = chr(ord('A') + idx)
        if isinstance(opt, dict):
            text = str(opt.get('text', '')).strip()
            if opt.get('key'):
                key = str(opt['key']).strip().upper()[:1] or key
        else:
            text = str(opt).strip()
            # "A) ..." style
            if len(text) >= 3 and text[1] == ')' and text[0].isalpha():
                key = text[0].upper()
                text = text[2:].strip()
        options.append({'key': key, 'text': text})

        # Identify correct option
        if correct_raw:
            if correct_raw.upper().startswith(key):
                correct_key = key
            elif correct_raw.lower() == text.lower():
                correct_key = key

    while len(options) < 4:
        options.append({
            'key': chr(ord('A') + len(options)),
            'text': 'Distractor',
        })

    # Single-letter correct_answer string takes precedence when given cleanly
    if len(correct_raw) == 1 and correct_raw.isalpha():
        correct_key = correct_raw.upper()

    return {
        'question': str(raw.get('question', 'Question'))[:600],
        'options': options,
        'correct_answer': correct_key,
        'explanation': str(raw.get('explanation', ''))[:600],
    }


def ensure_quiz_questions(task: Task) -> List[dict]:
    """Populate `task.quiz_questions` if empty. Returns the list (always).

    Idempotent: once populated, subsequent calls are no-ops so retries see
    the same questions.
    """
    if task.quiz_questions:
        return task.quiz_questions

    count = task.required_questions()
    node = _pick_grounding_node(task)

    topic_title = task.title
    subject_name = ''
    content_context = ''
    grade_level = getattr(task.goal.student, 'grade_level', None)

    if node is not None:
        content_context = (node.content_plain or node.content or '').strip()
        topic_title = node.title or topic_title
        if node.subject_id:
            subject_name = node.subject.name

    if not subject_name and task.goal.subject_id:
        subject_name = task.goal.subject.name

    raw: List[dict] = []
    llm_configured = bool(getattr(settings, 'OPENAI_API_KEY', ''))
    if llm_configured:
        try:
            generator = QuestionGenerator()
            raw = generator.generate_questions(
                topic=topic_title,
                difficulty='medium',
                count=count,
                question_type='mcq',
                subject_context=subject_name,
                content_context=content_context,
                grade_level=grade_level,
            )
        except Exception as exc:
            logger.warning(
                'Hunt task quiz generation failed (task %s): %s — using stub',
                task.pk, exc,
            )

    if not raw:
        raw = _stub_questions(topic_title, count)

    normalized = [_normalize_question(r) for r in raw[:count]]

    # Pad if LLM returned fewer than requested
    while len(normalized) < count:
        normalized.extend(
            _normalize_question(r)
            for r in _stub_questions(topic_title, count - len(normalized))
        )

    task.quiz_questions = normalized[:count]
    task.save(update_fields=['quiz_questions', 'updated_at'])
    return task.quiz_questions


# ---------------------------------------------------------------------------
# grading
# ---------------------------------------------------------------------------

def grade_quiz(task: Task, responses: List[Dict]) -> dict:
    """Grade a quiz attempt.

    responses: `[{'qid': <index>, 'selected': '<A|B|C|D>'}, ...]`.
    Returns a result dict:
        {
            correct, total, pct, threshold, passed,
            details: [{qid, question, options, correct_answer,
                       selected, is_correct, explanation}, ...]
        }
    """
    questions = task.quiz_questions or []
    by_qid = {r.get('qid'): (r.get('selected') or '').strip().upper()[:1]
              for r in responses if isinstance(r, dict)}

    correct_count = 0
    details = []
    for idx, q in enumerate(questions):
        correct_key = (q.get('correct_answer') or '').strip().upper()[:1]
        selected = by_qid.get(idx, '')
        is_correct = bool(correct_key) and selected == correct_key
        if is_correct:
            correct_count += 1
        details.append({
            'qid': idx,
            'question': q.get('question', ''),
            'options': q.get('options', []),
            'correct_answer': correct_key,
            'selected': selected,
            'is_correct': is_correct,
            'explanation': q.get('explanation', ''),
        })

    total = len(questions)
    pct = int(round(100 * correct_count / total)) if total else 0
    threshold = task.pass_threshold_pct()
    return {
        'correct': correct_count,
        'total': total,
        'pct': pct,
        'threshold': threshold,
        'passed': pct >= threshold,
        'details': details,
    }
