# Generated by Django 5.1 on 2026-04-27 09:23

import apps.service.models.asset
import apps.service.models.document
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the class (e.g., Grade 8 - Section A)",
                        max_length=100,
                        verbose_name="Class Name",
                    ),
                ),
                (
                    "grade_level",
                    models.IntegerField(
                        help_text="Grade level (1-12)", verbose_name="Grade Level"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        default="A",
                        help_text="Section identifier (A, B, C, etc.)",
                        max_length=10,
                        verbose_name="Section",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Academic year (e.g., 2024-2025)",
                        max_length=20,
                        verbose_name="Academic Year",
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(
                        default=30,
                        help_text="Maximum number of students allowed in this class",
                        verbose_name="Maximum Students",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this class is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary teacher responsible for this class",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Class Teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["grade_level", "section"],
            },
        ),
        migrations.CreateModel(
            name="ContentNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(max_length=50)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("chapter", "Chapter"),
                            ("section", "Section"),
                            ("topic", "Topic"),
                            ("definition", "Definition"),
                            ("formula", "Formula"),
                            ("example", "Example"),
                            ("exercise", "Exercise"),
                            ("summary", "Summary"),
                            ("key_point", "Key Point"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True)),
                ("content_plain", models.TextField(blank=True)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "embedding_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="service.contentnode",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "page_number", "position"],
            },
        ),
        migrations.CreateModel(
            name="ContentCrossRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_type",
                    models.CharField(
                        choices=[
                            ("prerequisite", "Prerequisite"),
                            ("related", "Related"),
                            ("extends", "Extends"),
                            ("applies", "Applies"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_refs",
                        to="service.contentnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_refs",
                        to="service.contentnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.service.models.document.document_upload_path
                    ),
                ),
                ("file_type", models.CharField(max_length=10)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="service.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="contentnode",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_nodes",
                to="service.document",
            ),
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("table", "Table"),
                            ("diagram", "Diagram"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.service.models.asset.asset_upload_path,
                    ),
                ),
                ("structured_data", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True)),
                ("caption", models.TextField(blank=True)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("asset_ref_id", models.CharField(max_length=100)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "content_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="service.contentnode",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="service.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "page_number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the subject (e.g., Mathematics, English)",
                        max_length=100,
                        verbose_name="Subject Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the subject (e.g., MATH, ENG)",
                        max_length=20,
                        verbose_name="Subject Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the subject",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366F1",
                        help_text="Color code for UI display (hex format)",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for UI display",
                        max_length=50,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this subject is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="service.subject",
            ),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="service.subject",
            ),
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weekly schedule for this subject (days, times)",
                        verbose_name="Schedule",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="service.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher assigned to teach this subject for this class",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taught_subjects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teacher",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="service.subject",
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Subject",
                "verbose_name_plural": "Class Subjects",
                "ordering": ["class_obj", "subject"],
            },
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["tenant", "academic_year", "is_active"],
                name="service_cla_tenant__0cac9a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("tenant", "grade_level", "section", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="contentcrossref",
            unique_together={("source_node", "target_node", "ref_type")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["tenant", "is_active"], name="service_sub_tenant__210d29_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "status"], name="service_doc_tenant__54281f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(
                fields=["document", "node_type"], name="service_con_documen_632fa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(
                fields=["document", "parent"], name="service_con_documen_cc22c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(
                fields=["subject"], name="service_con_subject_9cd515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["class_obj", "is_active"], name="service_cla_class_o_c11548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["teacher", "is_active"], name="service_cla_teacher_0dc333_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_obj", "subject")},
        ),
    ]
