# Generated by Django 5.1 on 2026-04-27 13:28

import apps.service.models.document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("synthetic", "Synthetic")],
                db_index=True,
                default="pdf",
                help_text="Origin of this document: a real uploaded PDF or seeded synthetic content.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Source file. Optional: synthetic books have no file attached.",
                null=True,
                upload_to=apps.service.models.document.document_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "source_type"], name="service_doc_tenant__828b28_idx"
            ),
        ),
    ]
