# Generated by Django 5.1 on 2026-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_contentembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-form per-turn metadata. For assistant turns this carries the router decision (routed subject / topics / intent / refined query) so the UI can render a subject chip and we can slice analytics.",
            ),
        ),
    ]
