# Generated by Django 5.1 on 2026-05-03 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_chatmessage_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enrolled_on", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="service.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="enrolled_classes",
                through="service.Enrollment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MissionBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("all_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_briefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MissionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("quest", "Quest"),
                            ("hunt_task", "Hunt Task"),
                            ("practice", "Practice"),
                            ("chat", "Chat"),
                            ("streak", "Streak"),
                            ("urgent_quest", "Urgent Quest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=0)),
                ("priority", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "related_object_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="service.missionbrief",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                ("step_1_identity", models.JSONField(blank=True, default=dict)),
                ("step_2_learning_style", models.JSONField(blank=True, default=dict)),
                ("step_3_goal", models.JSONField(blank=True, default=dict)),
                ("step_4_aptitude", models.JSONField(blank=True, default=dict)),
                (
                    "calibrated_rank",
                    models.CharField(blank=True, default="E", max_length=1),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hunter_title",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("E", "E"),
                            ("D", "D"),
                            ("C", "C"),
                            ("B", "B"),
                            ("A", "A"),
                            ("S", "S"),
                        ],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("streak_days", models.PositiveIntegerField(default=0)),
                (
                    "streak_shields_remaining",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("last_active_date", models.DateField(blank=True, null=True)),
                ("last_shield_refill_date", models.DateField(blank=True, null=True)),
                ("daily_xp_earned", models.PositiveIntegerField(default=0)),
                ("daily_xp_reset_date", models.DateField(blank=True, null=True)),
                (
                    "mastery_per_subject",
                    models.JSONField(
                        blank=True, default=dict, help_text="{subject_id: 0-100}"
                    ),
                ),
                (
                    "learning_style",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="VARK profile from onboarding",
                    ),
                ),
                ("interest_tags", models.JSONField(blank=True, default=list)),
                (
                    "onboarding_complete",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["class_obj", "is_active"], name="service_enr_class_o_11021f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "is_active"], name="service_enr_student_f09f05_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("class_obj", "student")},
        ),
        migrations.AddIndex(
            model_name="missionbrief",
            index=models.Index(
                fields=["student", "-date"], name="service_mis_student_be4e95_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="missionbrief",
            unique_together={("student", "date")},
        ),
        migrations.AddIndex(
            model_name="missionitem",
            index=models.Index(
                fields=["brief", "status"], name="service_mis_brief_i_25ffbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missionitem",
            index=models.Index(
                fields=["brief", "-priority"], name="service_mis_brief_i_e2b71a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["student", "onboarding_complete"],
                name="service_stu_student_275e6e_idx",
            ),
        ),
    ]
