# Generated by Django 5.1 on 2026-05-03 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("service", "0006_enrollment_class_students_missionbrief_missionitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("instructions", models.TextField(blank=True, default="")),
                ("due_date", models.DateTimeField()),
                ("total_marks", models.PositiveIntegerField(default=0)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1 (easy) to 5 (hard); each star is ~20% XP multiplier.",
                    ),
                ),
                (
                    "reward_xp",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="XP awarded on 100% score. Auto-derived if 0 at save time.",
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="service.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="service.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("visit_chat", "Visit the System Advisor"),
                            ("practice_weakest", "Practice your weakest subject"),
                            ("hunt_task", "Complete a Hunt task"),
                            ("streak", "Maintain your streak"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("xp_reward", models.PositiveIntegerField(default=10)),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_quests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "kind"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("target_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("progress_pct", models.PositiveSmallIntegerField(default=0)),
                ("xp_reward", models.PositiveIntegerField(default=200)),
                ("decomposed_at", models.DateTimeField(blank=True, null=True)),
                ("decomposition_error", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="service.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple choice"),
                            ("short", "Short answer"),
                            ("essay", "Essay"),
                            ("upload", "File upload"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.JSONField(blank=True, default=list)),
                (
                    "correct_answer",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("explanation", models.TextField(blank=True, default="")),
                ("marks", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="service.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["assignment", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("max_score", models.PositiveIntegerField(default=0)),
                ("xp_awarded", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="service.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option_key",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("answer_text", models.TextField(blank=True, default="")),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="submissions/"),
                ),
                ("marks_awarded", models.PositiveIntegerField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="service.question",
                    ),
                ),
                (
                    "student_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="service.studentassignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("practice", "Practice"),
                            ("chat", "Chat"),
                            ("quiz", "Quiz"),
                            ("reflect", "Reflect"),
                            ("boss", "Boss"),
                        ],
                        default="practice",
                        max_length=20,
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=25)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="service.goal",
                    ),
                ),
                (
                    "ref_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hunt_tasks",
                        to="service.contentnode",
                    ),
                ),
            ],
            options={
                "ordering": ["goal", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="XPLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("quest", "Quest"),
                            ("hunt_task", "Hunt Task"),
                            ("hunt_complete", "Hunt Complete"),
                            ("daily_quest", "Daily Quest"),
                            ("streak_milestone", "Streak Milestone"),
                            ("awakening", "Awakening"),
                            ("chat_activity", "Chat Activity"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(help_text="Can be negative for corrections."),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "related_object_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["tenant", "class_obj", "status"],
                name="service_ass_tenant__ea23d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["tenant", "due_date"], name="service_ass_tenant__08df0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyquest",
            index=models.Index(
                fields=["student", "-date"], name="service_dai_student_a65af3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyquest",
            unique_together={("student", "date", "kind")},
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["student", "status"], name="service_goa_student_1cffb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["student", "target_date"], name="service_goa_student_2888a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["assignment", "order"], name="service_que_assignm_4fea7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentassignment",
            index=models.Index(
                fields=["student", "status"], name="service_stu_student_9fc174_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentassignment",
            index=models.Index(
                fields=["assignment", "status"], name="service_stu_assignm_029930_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentassignment",
            unique_together={("assignment", "student")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["student_assignment"], name="service_ans_student_a4f72e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("student_assignment", "question")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["goal", "is_completed"], name="service_tas_goal_id_acf96b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xpledger",
            index=models.Index(
                fields=["student", "-created_at"], name="service_xpl_student_c28f9f_idx"
            ),
        ),
    ]
