# Generated by Django 5.1 on 2026-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_assignment_dailyquest_goal_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="best_score_pct",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="quiz_questions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
