# Generated by hand — add preferences JSONField to StudentProfile.
# The streak engine (apps.service.services.streaks) stores per-student
# milestone-tracking state here. Other engines may reuse the bucket.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_task_best_score_pct_task_quiz_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Misc student preferences / engine state "
                    "(e.g. streak milestones hit)."
                ),
            ),
        ),
    ]
