# Generated by Django 5.1 on 2026-04-29 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Django settings attribute name. Must match exactly (case-sensitive).",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="String value applied to django.conf.settings at server startup.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("llm", "LLM"),
                            ("embedding", "Embedding"),
                            ("vector_store", "Vector store"),
                            ("tutoring", "Tutoring"),
                            ("platform", "Platform"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One-line note for the admin: where this is used / what it does.",
                        max_length=255,
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="When true, the value is masked in admin list views.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="If false, the row is ignored at startup and the .env fallback is used.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "App setting",
                "verbose_name_plural": "App settings",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "category"],
                        name="core_appset_is_acti_4c0425_idx",
                    )
                ],
            },
        ),
    ]
