# Generated by Django 5.1 on 2026-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the school or organization",
                        max_length=255,
                        verbose_name="School Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Unique subdomain identifier (e.g., "springfield" for springfield.eduai.com)',
                        max_length=100,
                        unique=True,
                        verbose_name="Subdomain",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text='Optional custom domain (e.g., "school.edu")',
                        max_length=255,
                        null=True,
                        verbose_name="Custom Domain",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive tenants cannot be accessed",
                        verbose_name="Active Status",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="School logo",
                        null=True,
                        upload_to="tenant_logos/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4F46E5",
                        help_text="Primary brand color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="School-specific configuration and preferences",
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
                (
                    "subscription_expires",
                    models.DateTimeField(
                        blank=True, help_text="Subscription expiration date", null=True
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(
                        default=100, help_text="Maximum number of students allowed"
                    ),
                ),
                (
                    "max_teachers",
                    models.IntegerField(
                        default=10, help_text="Maximum number of teachers allowed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_active"], name="tenants_ten_slug_7c647c_idx"
                    )
                ],
            },
        ),
    ]
