# Generated by Django 5.1 on 2026-04-16 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the class (e.g., Grade 8 - Section A)",
                        max_length=100,
                        verbose_name="Class Name",
                    ),
                ),
                (
                    "grade_level",
                    models.IntegerField(
                        help_text="Grade level (1-12)", verbose_name="Grade Level"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        default="A",
                        help_text="Section identifier (A, B, C, etc.)",
                        max_length=10,
                        verbose_name="Section",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Academic year (e.g., 2024-2025)",
                        max_length=20,
                        verbose_name="Academic Year",
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(
                        default=30,
                        help_text="Maximum number of students allowed in this class",
                        verbose_name="Maximum Students",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this class is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary teacher responsible for this class",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Class Teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["grade_level", "section"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the subject (e.g., Mathematics, English)",
                        max_length=100,
                        verbose_name="Subject Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the subject (e.g., MATH, ENG)",
                        max_length=20,
                        verbose_name="Subject Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the subject",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366F1",
                        help_text="Color code for UI display (hex format)",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for UI display",
                        max_length=50,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this subject is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weekly schedule for this subject (days, times)",
                        verbose_name="Schedule",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="common.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher assigned to teach this subject for this class",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taught_subjects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teacher",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="common.subject",
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Subject",
                "verbose_name_plural": "Class Subjects",
                "ordering": ["class_obj", "subject"],
            },
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["tenant", "academic_year", "is_active"],
                name="common_clas_tenant__43650a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("tenant", "grade_level", "section", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["tenant", "is_active"], name="common_subj_tenant__af0f23_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["class_obj", "is_active"], name="common_clas_class_o_a1321f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["teacher", "is_active"], name="common_clas_teacher_d5f962_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_obj", "subject")},
        ),
    ]
